### ISSUE TITLE
[URGENT] Chat Markdown crashes on some input

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#127]
Steps to reproduce:
(1) Input the following text in the chat box
```text
`code`
```
(2) Click the `Send` button
(3) The chat message is not sent. The following error shown in the console:
```text
TypeError: Cannot read properties of undefined (reading 'inTable')
    at Object.exitCodeText (index.js:123:17)
    at compile (index.js:363:40)
    at fromMarkdown (index.js:193:30)
    at parser (index.js:18:12)
    at Function.parse (index.js:273:12)
    at Object.fn (dev.jsx:310:50)
    at runComputation (dev.js:720:22)
    at updateComputation (dev.js:702:3)
    at createMemo (dev.js:263:10)
    at SolidMarkdown (dev.jsx:299:24)
```

Environment: Edge 127.0.2651.86

**Comment by zjkmxy** [comment]
@AnoldGH Please fix and run a full test on input.

**Comment by AnoldGH** [comment]
The error was introduced by `SolidMarkdown` using `remark-gfm` version `3.0.1` instead of `4.0.0`. I accidentally overwrote the dependencies before pushing, apology. I will fix it quickly.

**Comment by zjkmxy** [comment]
> The error was introduced by specifying `remark-gfm` version `4.0.0` instead of `3.0.1` in `package.json`. I accidentally overwrote the dependencies before pushing, apology. I will fix it quickly.

Oh, that was introduced when I resolved the conflict. Don't know why but let me merge your fix.
